name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci
      - run: npm run lint
      - run: npm run format
      - run: npm run test
      - run: npm run build

      # Generate documentation
      - name: Generate Documentation
        run: npm run generate-docs

      # Deploy to GitHub Pages
      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

      # Uncomment the following lines when you are ready to publish to npm.
      # Make sure to add a "version" script in your package.json for npm versioning.
      # - name: Version and Tag
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: npm version patch -m "Bump version to %s"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish to npm
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
